package me.agno.gridjavacore.columns;

import me.agno.gridjavacore.IGrid;

public interface IGridColumn<T> extends IColumn<T>, ISortableColumn<T>, IFilterableColumn<T>,
        ISearchableColumn<T>, ITotalsColumn<T>
{
    IGrid<T> getParentGrid();

    boolean isHidden();

    void setHidden(boolean hidden);

    boolean isPrimaryKey();

    boolean isAutoGeneratedKey();
}