package me.agno.gridjavacore.columns;

import me.agno.gridjavacore.IGrid;

/**
 * Represents a column in a grid that implements several interfaces for sorting, filtering, searching, and calculation.
 *
 * @param <T> the type of data in the column
 */
public interface IGridColumn<T> extends IColumn<T>, ISortableColumn<T>, IFilterableColumn<T>,
        ISearchableColumn<T>, ITotalsColumn<T> {

    /**
     * Retrieves the parent grid of a column.
     *
     * @return the parent grid of the column
     */
    IGrid<T> getParentGrid();

    /**
     * Checks if the column is hidden.
     *
     * @return {@code true} if the column is hidden, {@code false} otherwise
     */
    boolean isHidden();

    /**
     * Sets whether the column is hidden.
     *
     * @param hidden {@code true} to hide the column, {@code false} to show the column
     */
    void setHidden(boolean hidden);

    /**
     * Checks whether the column is a primary key column.
     *
     * @return {@code true} if the column is a primary key column, {@code false} otherwise
     */
    boolean isPrimaryKey();

    /**
     * Determines whether the column is an auto-generated key column.
     *
     * @return {@code true} if the column is an auto-generated key column, {@code false} otherwise
     */
    boolean isAutoGeneratedKey();
}