package me.agno.gridcore.columns;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;
import me.agno.gridcore.IGrid;
import me.agno.gridcore.IGridColumnCollection;
import me.agno.gridcore.filtering.ColumnFilterValue;
import me.agno.gridcore.filtering.GridFilterType;
import me.agno.gridcore.filtering.IColumnFilter;
import me.agno.gridcore.searching.IColumnSearch;
import me.agno.gridcore.sorting.GridSortDirection;
import me.agno.gridcore.sorting.GridSortMode;
import me.agno.gridcore.sorting.IColumnOrderer;
import me.agno.gridcore.totals.IColumnTotals;
import me.agno.gridcore.totals.Total;
import me.agno.gridcore.utils.QueryDictionary;

import java.util.Collection;
import java.util.Optional;
import java.util.function.Function;

public abstract class GridCoreColumnBase<T, TData> implements IGridColumn<T>
{

    @Getter
    @Setter(AccessLevel.PROTECTED)
    private boolean ColumnSortDefined = false;

    @Getter
    @Setter(AccessLevel.PROTECTED)
    private boolean SortEnabled;

    @Getter
    @Setter(AccessLevel.PROTECTED)
    private GridSortMode SortMode = GridSortMode.ThreeState;

    @Getter
    @Setter
    private String Name;

    @Getter
    @Setter
    private String FieldName;

    @Getter
    @Setter
    private boolean Sorted;

    private Optional<GridSortDirection> _direction;

    public Optional<GridSortDirection> getDirection() {
        return _direction;
    }

    public void setDirection(GridSortDirection direction) {
        _direction = Optional.ofNullable(direction);
    }

    private Optional<GridSortDirection> _initialDirection;

    public Optional<GridSortDirection> getInitialDirection() {
        return _initialDirection;
    }

    public void setInitialDirection(GridSortDirection initialDirection) {
        _initialDirection = Optional.ofNullable(initialDirection);
    }

    @Getter
    @Setter
    private boolean Hidden;

    @Getter
    private boolean PrimaryKey = false;

    public IGridColumn<T> setPrimaryKey(boolean enabled) {
        return setPrimaryKey(enabled, true);
    }

    public IGridColumn<T> setPrimaryKey(boolean enabled, boolean autoGenerated) {
        PrimaryKey = enabled;
        AutoGeneratedKey = autoGenerated;
        return this;
    }

    @Getter
    @Setter(AccessLevel.PROTECTED)
    private boolean AutoGeneratedKey = false;

    @Getter
    @Setter
    private boolean SumEnabled = false;

    @Getter
    @Setter
    private boolean AverageEnabled = false;

    @Getter
    @Setter
    private boolean MaxEnabled = false;

    @Getter
    @Setter
    private boolean MinEnabled = false;

    @Getter
    @Setter
    public boolean CalculationEnabled = false;

    @Getter
    @Setter
    private QueryDictionary<Function<IGridColumnCollection<T>, Object>> Calculations;

    @Getter
    @Setter
    private QueryDictionary<Total> CalculationValues;

    @Getter
    @Setter
    private Total SumValue;

    @Getter
    @Setter
    private Total AverageValue;

    @Getter
    @Setter
    private Total MaxValue;

    @Getter
    @Setter
    private Total MinValue;

    public IGridColumn<T> sum(boolean enabled) {
        SumEnabled = enabled;
        return this;
    }

    public IGridColumn<T> average(boolean enabled) {
        AverageEnabled = enabled;
        return this;
    }

    public IGridColumn<T> max(boolean enabled) {
        MaxEnabled = enabled;
        return this;
    }

    public IGridColumn<T> min(boolean enabled) {
        MinEnabled = enabled;
        return this;
    }

    public IGridColumn<T> calculate(String name, Function<IGridColumnCollection<T>, Object> calculation) {
        CalculationEnabled = true;
        Calculations.AddParameter(name, calculation);
        return this;
    }

    @Getter
    private IGrid<T> ParentGrid;

    public IGridColumn<T> SetInitialFilter(GridFilterType type, String value) {
        var filter = new ColumnFilterValue(getName(), type, value);
        setInitialFilterSettings(filter);
        return this;
    }

    public abstract IGridColumn<T> SortInitialDirection(GridSortDirection direction);

    public abstract <TData>  IGridColumn<T> thenSortBy(Function<T, TData> expression);

    public abstract <TData> IGridColumn<T> thenSortByDescending(Function<T, TData> expression);

    @Getter
    private Collection<IColumnOrderer<T>> Orderers;

    public abstract IGridColumn<T> sortable(boolean sort);

    public abstract IGridColumn<T> sortable(boolean sort, GridSortMode gridSortMode);


    abstract IGridColumn<T> internalSortable(boolean sort);

    abstract IGridColumn<T> internalSortable(boolean sort, GridSortMode gridSortMode);

    @Getter
    @Setter
    private boolean FilterEnabled;

    @Getter
    @Setter
    private ColumnFilterValue InitialFilterSettings;

    public abstract IGridColumn<T> filterable(boolean showColumnValuesVariants);


    public abstract IGridColumn<T> SetFilterWidgetType(Object widgetData);

    @Getter
    private IColumnFilter Filter;

    @Getter
    private String FilterWidgetTypeName;

    @Getter
    @Setter(AccessLevel.PROTECTED)
    private Object FilterWidgetData;

    @Getter
    private IColumnSearch<T> Search;

    @Getter
    private IColumnTotals<T, TData> Totals;
}
