package me.agno.gridcore.columns;

import me.agno.gridcore.IGridColumnCollection;

import java.util.function.Function;

public interface IColumn<T> {

    String getName();

    String getFieldName();

    void setFieldName(String fieldName);

    IGridColumn<T> Sum(boolean enabled);

    IGridColumn<T> Average(boolean enabled);

    IGridColumn<T> Max(boolean enabled);

    IGridColumn<T> Calculate(String name, Function<IGridColumnCollection<T>, Object> calculation);

    IGridColumn<T> Min(boolean enabled);

    IGridColumn<T> SetPrimaryKey(boolean enabled);

    IGridColumn<T> SetPrimaryKey(boolean enabled, boolean autoGenerated);
}
