package me.agno.gridcore.columns;

import me.agno.gridcore.utils.IGrid;

import java.util.function.Function;

public interface IGridColumn<T> extends IColumn<T>, ISortableColumn<T>, IFilterableColumn<T>,
        ISearchableColumn<T>, ITotalsColumn<T>
{
    IGrid getParentGrid();

    boolean isHidden();

    void setHidden(boolean hidden);

    boolean isPrimaryKey();

    boolean isAutoGeneratedKey();

    void SetGroupLabel(Function<Object, String> function);
}